server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      sivalabs: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog?useSSL=false
    username: root
    password: admin
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
